version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: web-container
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_ENV=${VITE_ENV}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    env_file:
      - .env
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
